shellEmulator: true

trustPolicy: no-downgrade
packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.4.3
  '@nuxt/content': ^3.11.2
  '@nuxt/eslint': ^1.15.1
  '@nuxt/icon': ^2.2.1
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.2.3
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  cheerio: ^1.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.2
  giget: ^3.1.2
  lint-staged: ^16.2.7
  lucide-vue-next: ^0.545.0
  marked: ^17.0.2
  nuxt: ^4.3.1
  oxlint: ^1.47.0
  oxnode: ^0.0.34
  picocolors: ^1.1.1
  reka-ui: 2.8.0
  rimraf: ^6.1.2
  simple-git-hooks: ^2.13.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tinyexec: ^1.0.2
  turbo: ^2.8.7
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vue: ^3.5.28
  vue-router: ^4.6.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
