shellEmulator: true

trustPolicy: no-downgrade
packages:
  - apps/*
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.2.0
  '@nuxt/content': ^3.10.0
  '@nuxt/eslint': ^1.12.1
  '@nuxt/icon': ^2.1.1
  '@tailwindcss/vite': ^4.1.18
  '@types/node': ^25.0.10
  '@vueuse/nuxt': ^14.1.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  eslint: ^9.39.2
  lint-staged: ^16.2.7
  lucide-vue-next: ^0.545.0
  nuxt: ^4.2.2
  picocolors: ^1.1.1
  reka-ui: ^2.7.0
  simple-git-hooks: ^2.13.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.6
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vue: ^3.5.26
  vue-router: ^4.6.4

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
